openapi: "3.1.0"
info:
  title: "gestion Conge API"
  version: "0.1.0"
  description: "gestion de conge API application made with Express and documented with Swagger"
  contact:
    name: "Montassar"
    url: "https://www.linkedin.com/in/montassar-front-end-dev/"
    email: "montassarthemri@gmail.com"
servers:
  - url: "http://localhost:5000/"
    description: "Development server"
paths:
  /api/users/register:
    post:
      summary: Create a new user.
      tags:
        - User
      consumes:
        - application/json
      produces:
        - application/json
      parameters: []
      requestBody:
        description: User data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequestBody'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
  /api/users/login:
    post:
      summary: Login as a user.
      tags:
        - User
      consumes:
        - application/json
      produces:
        - application/json
      parameters: []
      requestBody:
        description: User login data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
components:
  schemas:
    UserRequestBody:
      type: object
      properties:
        firstName:
          type: string
          minLength: 5
        lastName:
          type: string
          minLength: 5
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 6
          maxLength: 20
      required:
        - firstName
        - lastName
        - email
        - password
    UserResponse:
      type: object
      properties:
        savedUser:
          $ref: '#/components/schemas/User'
        message:
          type: string
